feat : merge

diff --git a/api/Tdev702.Api/Dockerfile b/api/Tdev702.Api/Dockerfile
--- a/api/Tdev702.Api/Dockerfile
+++ b/api/Tdev702.Api/Dockerfile
@@ -21,16 +21,19 @@ RUN apt-get update && apt-get install -y \
 FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
 ARG BUILD_CONFIGURATION=Release
 WORKDIR /src
-
 COPY . .
+
+RUN echo "Contents of /src after COPY:" && \
+    ls -la && \
+    echo "Contents of /src/Tdev702.Api (if it exists):" && \
+    ls -la Tdev702.Api || echo "Tdev702.Api directory not found
 RUN dotnet restore "Tdev702.Api/Tdev702.Api.csproj"
 
-WORKDIR "/src/Tdev702.Api"
-RUN dotnet build "Tdev702.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build
+RUN dotnet build "Tdev702.Api/Tdev702.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build
 
 FROM build AS publish
 ARG BUILD_CONFIGURATION=Release
-RUN dotnet publish "Tdev702.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
+RUN dotnet publish "Tdev702.Api/Tdev702.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
 
 FROM base AS final
 WORKDIR /app
